apiVersion: v1
kind: ConfigMap
metadata:
  name: loantrack-config
  namespace: loantrack
data:
  POSTGRES_DB: loantrack
  POSTGRES_USER: loantrack_user
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  BACKEND_PORT: "8000"